# Generated by Django 4.0.6 on 2022-07-20 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('genres', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                (
                    'cart_uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('total', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='carts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                (
                    'movie_uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=127, unique=True)),
                ('run_time', models.CharField(max_length=10)),
                ('year', models.DateField(null=True)),
                ('classification', models.PositiveIntegerField()),
                ('synopsis', models.TextField()),
                ('price', models.FloatField()),
                (
                    'carts',
                    models.ManyToManyField(
                        related_name='movies',
                        through='movies.Cart',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'genres',
                    models.ManyToManyField(
                        related_name='movies', to='genres.genre'
                    ),
                ),
                (
                    'stock',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='movie',
                        to='stocks.stock',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='movies',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.movie'
            ),
        ),
    ]
